export const PHONE_UPPER_BOUND = '600px'
export const TABLET_PORTRAIT_UPPER_BOUND = '900px'
export const TABLET_LANDSCAPE_UPPER_BOUND = '1200px'
export const DESKTOP_UPPER_BOUND = '1800px'
export const LEND = 'LEND'
export const BORROW = 'BORROW'
export const WITHDRAW = 'WITHDRAW'
export const REPAY = 'REPAY'
